#!/bin/bash

env

TAG=${SOURCE_BRANCH}_swift-4.0
docker tag $IMAGE_NAME $DOCKER_REPO:$TAG
docker push $DOCKER_REPO:$TAG

docker tag $IMAGE_NAME $DOCKER_REPO:$SOURCE_BRANCH
docker push $DOCKER_REPO:$SOURCE_BRANCH

docker tag $IMAGE_NAME $DOCKER_REPO:latest
docker push $DOCKER_REPO:latest

exit $?
