#!/bin/bash

env

TAG=${SOURCE_BRANCH}_swift-3.1
docker tag $IMAGE_NAME $DOCKER_REPO:$TAG
docker push $DOCKER_REPO:$TAG

TAG=${SOURCE_BRANCH}_swift-3.1.1
docker tag $IMAGE_NAME $DOCKER_REPO:$TAG
docker push $DOCKER_REPO:$TAG

exit $?
